// Generated by CoffeeScript 1.6.3
var request, setup, should;

request = require('request');

should = require('should');

setup = require('./_setup')._setup;

describe('Testing mongodb connection', function() {
  before(function(done) {
    return setup.init(done);
  });
  return it('Should be able to connect via direct api', function(done) {
    setup.api.mongo.db.collection('foo').find({}, function(err, result) {
      return should.not.exist(err);
    });
    return done();
  });
});
